config/routes.rb
QuestionAndAnswer::Application.routes.draw do

  root to: 'questions#index'

  resources :questions do
    member do
      get 'vote'
    end
    collection do
      get 'unanswered'
      get 'search'
      get 'mine'
    end
  	resources :comments, :only => [:create, :update, :destroy, :index]
  	resources :answers
  end

  resources :answers do
  	member do
  		get 'vote'
      get 'correct'
  	end
  	resources :comments, :only => [:create, :update, :destroy, :index]
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
	include Tire::Model::Search
	include Tire::Model::Callbacks
	include Taggable
	include Votable
	# include ThinkingSphinx::Scopes

  mapping do
    indexes :id, :index    => :not_analyzed
    indexes :subject, :analyzer => 'snowball', :boost => 100
    indexes :content, :analyzer => 'snowball'
    indexes :created_at, :type => 'date'
    indexes :user_id , :index => :not_analyzed
	  indexes :up_votes, :index => :not_analyzed
	  indexes :down_votes, :index => :not_analyzed

    indexes :tags do
      indexes :name, :analyzer => 'keyword'
    end
  end


	belongs_to :spud_user, :foreign_key => :user_id
	has_many :answers
	has_many :comments, :as => :attachment

	validates :subject, :presence => true
	validates :content, :presence => true

	scope :unanswered, joins("LEFT JOIN answers on answers.question_id = questions.id").group("questions.id").having("count(answers.id) = 0")

	def formatted_content
		if self.content.blank?
			return ''
		end
		require 'redcarpet'
	    renderer = Redcarpet::Render::HTML.new
	    extensions = {fenced_code_blocks: true}
	    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
	    redcarpet.render self.content
	end

	def self.search(phrase)
	  tire.search(load: true) do
	    query { string phrase, default_operator: "AND" } if phrase.present?
	    # filter :range, published_at: {lte: Time.zone.now}
	  end
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :require_user
	respond_to :html, :json

	def index
		order = params[:order] || "updated_at DESC"
		page  = params[:page] || 1

		@questions = Question.order(order).includes(:answers).paginate :page => page
		respond_with @questions
	end

	def search
		@results = Question.search params[:phrase]
		respond_with @results
	end

	def unanswered
		order = params[:order] || "updated_at DESC"
		page  = params[:page] || 1

		@questions = Question.unanswered.includes(:answers).order(order).paginate :page => page
		render :action => "index"
	end

	def mine
		order = params[:order] || "updated_at DESC"
		page  = params[:page] || 1

		@questions = Question.where(:user_id => @current_user.id).order(order).includes(:answers).paginate :page => page
		render :action => "index"
	end

	def tags
		order = params[:order] || "updated_at DESC"
		page  = params[:page] || 1

		# @questions = Question.tags(params[:id]).order(order).includes(answers).paginate :page => page
		render :action => "index"
	end

	def show
		@question = Question.find(params[:id])
		@answers = @question.answers.order(:created_at).all
		@answer = @question.answers.new
		respond_with @question
	end

	def new
		@question = Question.new(:spud_user => @current_user)
		respond_with @question
	end

	def create
		@question = Question.new(question_params)
		@question.spud_user = @current_user
		@question.save
		respond_with @question
	end

	def edit
		@question = Question.find(params[:id])
		respond_with @question
	end

	def update
		@question = Question.find(params[:id])
		@question.update_attributes(question_params)
		respond_with @question
	end

	def destroy
		@question = Question.find(params[:id])
		if @question.spud_user != @current_user
			flash[:error] = "You do not have permission to remove this question!"
			redirect_to request.referer || questions_url
			return
		end

		@question.destroy

		respond_with @question
	end

	def vote
		@question = Question.find(params[:id])
		response = @question.vote(@current_user, params[:value])
		redirect_to :back
	end

private
	def question_params
		params.require(:question).permit(:subject,:content,:tag_string)
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
	<div class="control-group">
		<%=f.label :subject, :class => "control-label"%>
		<div class="controls">
			<%=f.text_field :subject%>
		</div>
	</div>
	<div class="control-group">
		<%=f.label :content, "Question", :class => "control-label"%>
		<div class="controls">
			<%=f.text_area :content, :class=>"question-field"%>
		    <span class="help-block">Markdown format Supported.</span>
		</div>
	</div>
	<div class="control-group">
		<%=f.label :tag_string, "Tags", :class => "control-label"%>
		<div class="controls">
			<%=f.text_field :tag_string%>
		    <span class="help-block">A comma delimited list of tags for this question.</span>
		</div>
	</div>

app/views/questions/_question.html.erb
<div class="question row-fluid">
	<div class="votes span1">
		<%=link_to "Up Vote", vote_question_url(:id => question.id,:value => 1), :class => "up-vote-btn"%>
		<span class="vote_count"><%=question.total_votes%></span>
		<%=link_to "Down Vote", vote_question_url(:id => question.id,:value => -1), :class => "down-vote-btn"%>
		<%if editable && @current_user.id == question.user_id%>
		<div class="btn-group edit-buttons">
			<%=link_to edit_question_url(question), :class => "btn btn-mini" do%>
				<i class="icon-pencil"></i>
			<%end%>
			<%=link_to question_url(question), :method => :delete, :confirm => "Are you sure you wish to remove this question?", :class => "btn btn-danger btn-mini" do%>
				<i class="icon-trash icon-white"></i>
			<%end%>

		</div>
		<%end%>
	</div>
	<div class="question_content span11">
		<h3><%=link_to question.subject, question_path(question)%></h3>
		<%=question.formatted_content.html_safe%>
		<div class="question_meta">
			<span class="posted_by">Asked By: <%=question.spud_user.full_name%></span>
			<span class="posted_at"><%=timestamp question.created_at%></span>
		</div>
		<div class="question-tags">
			<%if question.tag_names.count > 0%>
			<strong>Tags: </strong>&nbsp;
				<%question.tag_names.each do |tag| %>
					<span class="label label-info"><%=tag%></span>
				<%end%>
			<%end%>
		</div>
	</div>
</div>

app/views/questions/edit.html.erb
<h1>New Question</h1>
<hr/>
<%=form_for @question, :html => {:class => "form-horizontal well"} do |f|%>
	<%= render :partial => "form", :locals => {:f => f}%>
	<div class="control-group">
		<div class="controls">
			<%=f.submit "Ask Question", :class => "btn btn-primary"%>
		</div>
	</div>
<%end%>

app/views/questions/index.html.erb
<div class="questions">
	<%=render :partial => "question", :collection => @questions, :locals => {:editable => false}%>
</div>
<%=will_paginate @questions%>

app/views/questions/new.html.erb
<h1>New Question</h1>
<hr/>
<%=form_for @question, :html => {:class => "form-horizontal well"} do |f|%>
	<%= render :partial => "form", :locals => {:f => f}%>
	<div class="control-group">
		<div class="controls">
			<%=f.submit "Ask Question", :class => "btn btn-primary"%>
		</div>
	</div>
<%end%>

app/views/questions/search.html.erb
<div class="questions">
	<%@results.each do |question|%>
		<div class="question row-fluid">
			<div class="votes span1">
				<%=link_to "Up Vote", vote_question_url(:id => question.id,:value => 1), :class => "up-vote-btn"%>
				<span class="vote_count"><%=question.total_votes%></span>
				<%=link_to "Down Vote", vote_question_url(:id => question.id,:value => -1), :class => "down-vote-btn"%>

			</div>
			<div class="question_content span11">
				<h3><%=link_to question.subject, question_path(question)%></h3>
				<%=question.formatted_content.html_safe%>
				<div class="question_meta">
					<span class="posted_by">Asked By: <%=question.spud_user.full_name%></span>
					<span class="posted_at"><%=timestamp question.created_at%></span>
				</div>
				<div class="question-tags">
					<%if question.tag_names.count > 0%>
					<strong>Tags: </strong>&nbsp;
						<%question.tag_names.each do |tag| %>
							<span class="label label-info"><%=tag%></span>
						<%end%>
					<%end%>
				</div>
			</div>
		</div>

	<%end%>
</div>
<%=will_paginate @results%>

app/views/questions/show.html.erb
<h2>Question</h2>
<%=render :partial => "question", :locals => {:editable => true, :question => @question}%>

<hr/>
<%if @answers.blank? == false %>
	<h2>Answers</h2>
	<%=render :partial => "/answers/answer", :collection => @answers%>
	<hr/>
<%end%>
<h2>Your answer</h2>
<%=form_for @answer, :url => question_answer_path(@question,@answer), :html => {:class => "form-horizontal well"} do |f|%>
	<div class="control-group">
		<%=f.label :content, "Answer", :class => "control-label"%>
		<div class="controls">
			<%=f.text_area :content, :class=>"question-field"%>
		    <span class="help-block">Markdown format Supported.</span>
		</div>
	</div>
	<div class="control-group">
		<div class="controls">
			<%=f.submit "Post your Answer", :class => "btn btn-primary"%>
		</div>
	</div>
<%end%>