config/routes.rb
QuestionAndAnswer::Application.routes.draw do

  root to: 'questions#index'

  resources :questions do
    member do
      get 'vote'
    end
    collection do
      get 'unanswered'
      get 'search'
      get 'mine'
    end
  	resources :comments, :only => [:create, :update, :destroy, :index]
  	resources :answers
  end

  resources :answers do
  	member do
  		get 'vote'
      get 'correct'
  	end
  	resources :comments, :only => [:create, :update, :destroy, :index]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	include Votable

	belongs_to :question
	belongs_to :spud_user, :foreign_key => :user_id
	has_many :comments, :as => :attachment


	def formatted_content
		if self.content.blank?
			return ''
		end
		require 'redcarpet'
	    renderer = Redcarpet::Render::HTML.new
	    extensions = {fenced_code_blocks: true}
	    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
	    redcarpet.render self.content
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	respond_to :json, :html
	before_filter :load_question, :except => [:vote,:correct]

	def create
		@answer = @question.answers.new(answer_params)
		@answer.spud_user = @current_user
		if @answer.save
        NotificationMailer.question_answered_notification(@question,@answer).deliver
		end
		respond_with @answer, :location => question_url(:id => @question.id)
	end

	def update
		@answer = @question.answers.find(params[:id])
		@answer.update_attributes(answer_params)
		respond_with @answer, :location => question_url(:id => @question.id)
	end

	def destroy
		@answer = @question.answers.find(params[:id])
		if @answer.user_id == @current_user.id
			@answer.destroy
		end
		respond_with @answer, :location => question_url(:id => @question.id)
	end

	def vote
		@answer = Answer.find(params[:id])
		response = @answer.vote(@current_user, params[:value])
		redirect_to :back and return
	end

	def correct
		@answer = Answer.find(params[:id])
		@question = @answer.question

		if @question.user_id != @current_user.id
			flash[:error] = "You must be the owner of the question to mark it."
		else
			@previously_marked_answer = @question.answers.where(:answered => true).first
			@previously_marked_answer.update_attributes(:answered => false) if @previously_marked_answer
			@answer.answered = true
			if @answer.save
        NotificationMailer.answer_correct(@answer).deliver
			end
		end
		redirect_to :back
	end

private
	def load_question
		@question = Question.find(params[:question_id])
	end

	def answer_params
		params.require(:answer).permit(:content)
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="answer row-fluid">
	<div class="votes span1">
		<%=link_to "Up Vote", vote_answer_url(:id => answer.id,:value => 1), :class => "up-vote-btn"%>
		<span class="vote_count"><%=answer.total_votes%></span>
		<%=link_to "Down Vote", vote_answer_url(:id => answer.id,:value => -1), :class => "down-vote-btn"%>
		<%if !answer.answered%>
			<%=link_to correct_answer_url(:id => answer.id), :class => "btn correct-answer-btn" do%>
				<i class="icon-ok "></i>
			<%end%>
		<%else%>
			<%=link_to correct_answer_url(:id => answer.id), :class => "btn btn-success correct-answer-btn" do%>
				<i class="icon-ok icon-white"></i>
			<%end%>
		<%end%>
	</div>
	<div class="answer_content span11">
		<%=answer.formatted_content.html_safe%>
		<div class="answer_meta">
			<span class="posted_by">Answered By: <%=answer.spud_user.try(:full_name)%></span>
			<span class="posted_at"><%=timestamp answer.created_at%></span>
		</div>
	</div>
</div>