config/routes.rb
QuestionAndAnswer::Application.routes.draw do

  root to: 'questions#index'

  resources :questions do
    member do
      get 'vote'
    end
    collection do
      get 'unanswered'
      get 'search'
      get 'mine'
    end
  	resources :comments, :only => [:create, :update, :destroy, :index]
  	resources :answers
  end

  resources :answers do
  	member do
  		get 'vote'
      get 'correct'
  	end
  	resources :comments, :only => [:create, :update, :destroy, :index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Question & Answer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Question &amp; Answer</a>
          <div class="nav-collapse collapse">
            <form class="navbar-search pull-left" action="/questions/search" method="GET">
              <input type="text" name="phrase" class="search-query" placeholder="Search" value="<%=params[:phrase]%>">
            </form>
            <ul class="nav">

              <li><a href="/">Questions</a></li>
              <li><a href="/questions/unanswered">Unanswered</a></li>
              <li><a href="/questions/mine">My Questions</a></li>
            </ul>
            <ul class="nav pull-right">
              <li><%=link_to new_question_url do%>
                <i class="icon-plus-sign icon-white"></i>&nbsp;Ask a Question
                <%end%>
              </li>


            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%=yield%>
    </div> <!-- /container -->

</body>
</html>